name: build & test

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: read

jobs:
  lint:
    runs-on: codeberg-tiny
    steps:
      - uses: actions/checkout@v6
      - uses: https://github.com/DeterminateSystems/nix-installer-action@v22
      - name: lint
        run: nix develop --command biome ci src/

  build:
    runs-on: codeberg-tiny
    steps:
    - uses: actions/checkout@v6
    
    - uses: actions/setup-node@v6
      with:
        node-version: '24.x'
        registry-url: 'https://npm.pkg.github.com'

    - name: install
      run: yarn install
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: build
      run: yarn run build

    - name: test
      run: yarn run coverage

    - name: Upload results to Codecov
      uses: https://github.com/codecov/codecov-action@v6
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
