name: build & test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: read

jobs:
  lint:
    runs-on: codeberg-tiny
    steps:
      - uses: actions/checkout@v4
      - uses: https://github.com/DeterminateSystems/nix-installer-action@v17
      - name: lint
        run: nix develop --command biome ci src/

  build:
    runs-on: codeberg-tiny
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://npm.pkg.github.com'

    - uses: https://github.com/DeterminateSystems/nix-installer-action@v17
    - uses: https://github.com/JRMurr/direnv-nix-action@v4.2.0

    - name: install
      run: yarn install
      env:
        NODE_AUTH_TOKEN: ${{ secrets.FORGEJO_TOKEN }}

    - name: build
      run: yarn run build

    - name: test
      run: yarn run coverage

    - name: Upload results to Codecov
      uses: https://github.com/codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
