name: pr lint

on: 
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: codeberg-tiny
    steps:
    - uses: actions/checkout@v4
    - uses: https://github.com/amannn/action-semantic-pull-request@v5
      env:
        FORGEJO_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
