name: pr lint

on: 
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: codeberg-tiny
    steps:
    - uses: actions/checkout@v4
    - uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
