name: release
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: codeberg-tiny
    steps:
      - uses: https://github.com/googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - uses: https://github.com/DeterminateSystems/nix-installer-action@v17
        if: ${{ steps.release.outputs.release_created }}

      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        run: |
          nix develop --command yarn install
          nix develop --command yarn run build

      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ steps.release.outputs.tag_name }} build/main.js build/styles.css manifest.json

