name: release nightly

on:
  pull_request:
    paths:
      - 'CHANGELOG.md'

permissions:
  contents: write
  pull-requests: write

jobs:
  release-nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v17

      - name: Build
        run: |
          nix develop --command yarn install
          nix develop --command yarn run build

      - name: Upload Release Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="$(cat package.json | nix run  nixpkgs#jq -- -r .version)-prerelease"
          gh release delete $VERSION --cleanup-tag -y || true
          gh release create $VERSION -p --latest=false -n ${{  }}
          gh release upload $VERSION --clobber build/main.js build/styles.css manifest.json
