name: release nightly
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v17

      - name: Build
        run: |
          nix develop --command yarn install
          nix develop --command yarn run build

      - name: Upload Release Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create nightly -p --latest=false || true
          gh release upload nightly --clobber build/main.js build/styles.css manifest.json

