name: release nightly

on:
  pull_request:
    paths:
      - 'CHANGELOG.md'

permissions:
  contents: write
  pull-requests: write

jobs:
  release-nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v17
      - uses: JRMurr/direnv-nix-action@v4.2.0

      - name: Build
        run: |
          yarn install
          yarn run build

      - name: Upload Release Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="$(cat package.json | jq -r .version)-prerelease"
          echo Version: $VERSION
          gh pr view --json body --jq .body
          gh release delete $VERSION --cleanup-tag -y || true
          gh release create $VERSION -p --latest=false -t "prelease of version: $VERSION" -n $(gh pr view --json body --jq .body | tail -n+4)
          gh release upload $VERSION --clobber build/main.js build/styles.css manifest.json
