name: release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write
  pull-requests: write
  id-token: write
  attestations: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
      - uses: DeterminateSystems/nix-installer-action@v22
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - uses: JRMurr/direnv-nix-action@v4.2.0

      - name: Build
        run: |
          yarn install
          yarn run build

      - name: artifact attestation
        uses: actions/attest@v4
        with:
          subject-path: |
            build/*
            manifest.json

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: ${{ github.ref_name }}
          generate_release_notes: false
          body: See the [changelog](https://github.com/Vinzent03/obsidian-git/blob/master/CHANGELOG.md) for details.
          draft: false
          prerelease: false
          files: |
            main.js
            manifest.json
            styles.css
