name: release
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
      - uses: oven-sh/setup-bun@v2
        if: ${{ steps.release.outputs.release_created }}

      - uses: DeterminateSystems/nix-installer-action@v14
        if: ${{ steps.release.outputs.release_created }}
      - uses: DeterminateSystems/magic-nix-cache-action@v8
        if: ${{ steps.release.outputs.release_created }}

      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        run: |
          nix develop --command yarn install
          nix develop --command yarn run build
      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} build/main.js build/styles.css manifest.json

