name: release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write
  pull-requests: write
  id-token: write
  attestations: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
      - uses: DeterminateSystems/nix-installer-action@v22
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - uses: JRMurr/direnv-nix-action@v4.2.0

      - name: Build
        run: |
          yarn install
          yarn run build

      - name: artifact attestation
        uses: actions/attest@v4
        with:
          subject-path: |
            build/*
            manifest.json

      - name: Upload Release Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.ref }} build/* manifest.json
